In [1]:
#import

In [2]:
from pandasql import sqldf
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#data

In [4]:
project_data = pd.read_excel('../data/TEIS-NSS Project Data 10-2022.xlsx', 
                             sheet_name=['ECO with Exit21-22', 'Elig Timeline Rpt 2018-2022'])

eco_exit = project_data.get('ECO with Exit21-22')
elig_timeline = project_data.get('Elig Timeline Rpt 2018-2022')
print(eco_exit)
print(elig_timeline)

                                               DISTRICT  CHILD_ID  \
0                                                    ET  500335.0
1                                                    ET  479453.0
2                                                    ET  510663.0
3                                                    ET  452482.0
4                                                    ET  506507.0
...                                                 ...       ...
8631                                                 UC  514216.0
8632                                                NaN       NaN
8633                                                NaN       NaN
8634                                                NaN       NaN
8635  9/29/22 JM Corrected in TEIDS. Progress would ...       NaN

     ECO_Entry_DATE  Ent SOCIAL_SCALE  Ent KNOWLEDGE_SCALE  \
0        2021-04-23               5.0                  3.0
1        2020-03-23               7.0                  7.0
2               NaT               NaN                  NaN
3        2019-01-31               2.0                  3.0
4               NaT               NaN                  NaN
...             ...               ...                  ...
8631            NaT               NaN                  NaN
8632            NaT               NaN                  NaN
8633            NaT               NaN                  NaN
8634            NaT               NaN                  NaN
8635            NaT               NaN                  NaN

      Ent APPROPRIATE_ACTION_SCALE ECO_Exit_DATE  Exit SOCIAL_SCALE  \
0                              4.0    2021-10-23                6.0
1                              7.0    2021-08-19                7.0
2                              NaN           NaT                NaN
3                              3.0    2021-11-22                5.0
4                              NaN           NaT                NaN
...                            ...           ...                ...
8631                           NaN           NaT                NaN
8632                           NaN           NaT                NaN
8633                           NaN           NaT                NaN
8634                           NaN           NaT                NaN
8635                           NaN           NaT                NaN

      Exit KNOWLEDGE_SCALE  Exit APPROPRIATE_ACTION_SCALE  ... OC2 Data Check  \
0                      3.0                            4.0  ...            1.0
1                      7.0                            7.0  ...            1.0
2                      NaN                            NaN  ...            0.0
3                      3.0                            5.0  ...            1.0
4                      NaN                            NaN  ...            0.0
...                    ...                            ...  ...            ...
8631                   NaN                            NaN  ...            0.0
8632                   NaN                            NaN  ...            NaN
8633                   NaN                            NaN  ...            NaN
8634                   NaN                            NaN  ...            NaN
8635                   NaN                            NaN  ...            NaN

     OC3 - a OC3 - b OC3 - c OC3 - d OC3 - e OC3 Data Check  \
0        NaN     1.0     NaN     NaN     NaN            1.0
1        NaN     NaN     NaN     NaN     1.0            1.0
2        NaN     NaN     NaN     NaN     NaN            0.0
3        NaN     NaN     1.0     NaN     NaN            1.0
4        NaN     NaN     NaN     NaN     NaN            0.0
...      ...     ...     ...     ...     ...            ...
8631     NaN     NaN     NaN     NaN     NaN            0.0
8632     NaN     NaN     NaN     NaN     NaN            NaN
8633     NaN     NaN     NaN     NaN     NaN            NaN
8634     NaN     NaN     NaN     NaN     NaN            NaN
8635     NaN     NaN     NaN     NaN     NaN            NaN

      Days btw Initial and Exit  Days btw I-IFSP to Exit ECO  \
0                         206.0                        183.0
1                         704.0                        514.0
2                         115.0                     -44483.0
3                        1053.0                       1026.0
4                         159.0                     -44434.0
...                         ...                          ...
8631                       65.0                     -44537.0
8632                        NaN                          NaN
8633                        NaN                          NaN
8634                        NaN                          NaN
8635                        NaN                          NaN

      Days btw I-IFSP to entry ECO
0                              0.0
1                              0.0
2                         -44483.0
3                              0.0
4                         -44434.0
...                            ...
8631                      -44537.0
8632                           NaN
8633                           NaN
8634                           NaN
8635                           NaN

[8636 rows x 60 columns]
      District  Child ID Child Status  Child Phase Init. IFSP Due Date  \
0           ET    453926     Inactive         IFSP          2019-03-04
1           ET    431729     Inactive         IFSP          2018-10-26
2           ET    462474     Inactive         IFSP          2019-06-28
3           ET    446841     Inactive  Eligibility          2018-11-23
4           ET    459629     Inactive         IFSP          2019-05-16
...        ...       ...          ...          ...                 ...
67605       UC    509553     Inactive         IFSP          2021-10-03
67606       UC    509684     Inactive         IFSP          2021-10-07
67607       UC    526338     Inactive         IFSP          2022-05-22
67608       UC    511641     Inactive  Eligibility          2021-11-22
67609       UC    519977     Inactive         IFSP          2022-03-07

      IFSP Due Date IFSP Late Reason Active Ref. Date  \
0        2019-03-27           System       2019-01-18
1        2018-10-26              NaN       2018-09-11
2        2019-06-14              NaN       2019-05-14
3               NaT              NaN       2018-10-09
4        2019-04-24              NaN       2019-04-01
...             ...              ...              ...
67605    2021-10-22           System       2021-08-19
67606    2021-09-07              NaN       2021-08-23
67607    2022-05-05              NaN       2022-04-07
67608           NaT              NaN       2021-10-08
67609    2022-02-03              NaN       2022-01-21

      Parent Consent/Intake Date Date Dev. Evaluator Rec'd. Ref.  ...  \
0                     2019-02-04             2019-01-22 00:00:00  ...
1                     2018-09-25             2018-09-12 00:00:00  ...
2                     2019-05-30             2019-05-15 00:00:00  ...
3                     2018-10-25             2018-10-11 00:00:00  ...
4                     2019-04-10             2019-04-02 00:00:00  ...
...                          ...                             ...  ...
67605                 2021-08-26             2021-08-23 00:00:00  ...
67606                 2021-08-31             2021-08-24 00:00:00  ...
67607                 2022-04-10             2022-04-08 00:00:00  ...
67608                 2021-10-18             2021-10-11 00:00:00  ...
67609                 2022-01-26             2022-01-24 00:00:00  ...

      # Days Parent Consent to Dev. Eval.  \
0                                    17.0
1                                     0.0
2                                     0.0
3                                     0.0
4                                     0.0
...                                   ...
67605                                 0.0
67606                                 0.0
67607                                 1.0
67608                                 0.0
67609                                 0.0

      # Days Dev. Evaluator Assigned to Dev. Eval.  \
0                                             30.0
1                                             13.0
2                                             15.0
3                                             14.0
4                                              8.0
...                                            ...
67605                                          3.0
67606                                          7.0
67607                                          3.0
67608                                          7.0
67609                                          2.0

      1st Date Requested to Receipt of Med. Records  \
0                                               NaN
1                                               NaN
2                                               0.0
3                                               NaN
4                                               0.0
...                                             ...
67605                                          35.0
67606                                           0.0
67607                                           0.0
67608                                           NaN
67609                                           0.0

      # Days Dev. Eval. to Elig. Det. # Days Ref. to Elig. Det.  \
0                                 4.0                      38.0
1                                 6.0                      20.0
2                                 1.0                      17.0
3                                 1.0                      17.0
4                                 2.0                      11.0
...                               ...                       ...
67605                            47.0                      54.0
67606                             2.0                      10.0
67607                             2.0                       6.0
67608                            11.0                      21.0
67609                             5.0                      10.0

      Init. Elig. Decision                           Init. Elig. Category  \
0                 Eligible                       Developmental Evaluation
1                 Eligible  Diagnosed Condition, Developmental Evaluation
2                 Eligible                       Developmental Evaluation
3                 Eligible                            Diagnosed Condition
4                 Eligible                       Developmental Evaluation
...                    ...                                            ...
67605             Eligible  Diagnosed Condition, Developmental Evaluation
67606             Eligible                       Developmental Evaluation
67607             Eligible                       Developmental Evaluation
67608             Eligible                            Diagnosed Condition
67609             Eligible                       Developmental Evaluation

      Init. Elig. Det. Date  Exit Date  \
0                2019-02-25 2020-01-11
1                2018-10-01 2020-12-11
2                2019-05-31 2020-11-12
3                2018-10-26 2020-08-12
4                2019-04-12 2019-09-26
...                     ...        ...
67605            2021-10-12 2021-12-10
67606            2021-09-02 2022-03-07
67607            2022-04-13 2022-07-25
67608            2021-10-29 2022-06-22
67609            2022-01-31 2022-06-20

                                   Exit Reason
0                        618 - Part B eligible
1      618 - Part B eligibility not determined
2      618 - Part B eligibility not determined
3                               Parent decline
4                        618 - Parent withdraw
...                                        ...
67605                 618 - Moved out of state
67606                    618 - Parent withdraw
67607                    618 - Parent withdraw
67608                           Parent decline
67609                    618 - Part B eligible

[67610 rows x 38 columns]

In [5]:
#rename

In [6]:
eco_exit = eco_exit.rename(columns={'DISTRICT':'district',
                                    'CHILD_ID':'child_id',
                                    'ECO_Entry_DATE':'eco_entry_date',
                                    'Ent SOCIAL_SCALE':'ent_social',
                                    'Ent KNOWLEDGE_SCALE':'ent_knowledge',
                                    'Ent APPROPRIATE_ACTION_SCALE':'ent_approp_action',
                                    'ECO_Exit_DATE':'eco_exit_date',
                                    'Exit SOCIAL_SCALE':'exit_social',
                                    'Exit KNOWLEDGE_SCALE':'exit_knowledge',
                                    'Exit APPROPRIATE_ACTION_SCALE':'exit_approp_action',
                                    'Days btw I-IFSP to Exit ECO' :'DBIexit'})

In [7]:
#ent_social = 3

In [8]:
eco_exit_1 = eco_exit[eco_exit['ent_social'] == 3.0]
eco_exit_1 = eco_exit[]

,district,child_id,eco_entry_date,ent_social,ent_knowledge,ent_approp_action,eco_exit_date,exit_social,exit_knowledge,exit_approp_action,...,OC2 Data Check,OC3 - a,OC3 - b,OC3 - c,OC3 - d,OC3 - e,OC3 Data Check,Days btw Initial and Exit,DBIexit,Days btw I-IFSP to entry ECO
11,ET,473375.0,2020-01-08,3.0,5.0,3.0,2022-03-29,7.0,7.0,7.0,...,1.0,NaN,NaN,NaN,1.0,NaN,1.0,836.0,834.0,23.0
13,ET,473208.0,2021-01-31,3.0,4.0,6.0,2021-12-15,5.0,1.0,4.0,...,1.0,NaN,1.0,NaN,NaN,NaN,1.0,493.0,350.0,32.0
32,ET,501251.0,2021-06-10,3.0,5.0,2.0,2022-04-29,3.0,6.0,7.0,...,1.0,NaN,NaN,NaN,1.0,NaN,1.0,356.0,343.0,20.0
39,ET,488505.0,2020-09-18,3.0,5.0,7.0,2021-08-11,6.0,7.0,7.0,...,1.0,NaN,NaN,NaN,NaN,1.0,1.0,510.0,327.0,0.0
44,ET,490266.0,2020-10-23,3.0,4.0,6.0,2021-09-28,5.0,5.0,7.0,...,1.0,NaN,NaN,NaN,NaN,1.0,1.0,501.0,340.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8606,UC,498301.0,2021-04-06,3.0,4.0,7.0,2022-04-05,7.0,7.0,7.0,...,1.0,NaN,NaN,NaN,NaN,1.0,1.0,443.0,364.0,0.0
8608,UC,484332.0,2020-07-22,3.0,2.0,4.0,2021-06-09,3.0,1.0,4.0,...,1.0,NaN,1.0,NaN,NaN,NaN,1.0,443.0,336.0,14.0
8614,UC,495409.0,2021-02-02,3.0,2.0,3.0,2021-08-04,6.0,4.0,5.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1.0,256.0,196.0,13.0
8621,UC,496165.0,2021-02-17,3.0,6.0,6.0,2022-02-10,7.0,7.0,7.0,...,1.0,NaN,NaN,NaN,NaN,1.0,1.0,434.0,358.0,0.0
8624,UC,490337.0,2020-11-09,3.0,1.0,1.0,2021-05-12,3.0,3.0,1.0,...,1.0,NaN,1.0,NaN,NaN,NaN,1.0,445.0,184.0,0.0

In [9]:
#eco_exit1 iloc

In [11]:
eco_exit1 = eco_exit.iloc[[3,4,5,7,8,9]]
print(eco_exit_1)

     district  child_id eco_entry_date  ent_social  ent_knowledge  \
11         ET  473375.0     2020-01-08         3.0            5.0
13         ET  473208.0     2021-01-31         3.0            4.0
32         ET  501251.0     2021-06-10         3.0            5.0
39         ET  488505.0     2020-09-18         3.0            5.0
44         ET  490266.0     2020-10-23         3.0            4.0
...       ...       ...            ...         ...            ...
8606       UC  498301.0     2021-04-06         3.0            4.0
8608       UC  484332.0     2020-07-22         3.0            2.0
8614       UC  495409.0     2021-02-02         3.0            2.0
8621       UC  496165.0     2021-02-17         3.0            6.0
8624       UC  490337.0     2020-11-09         3.0            1.0

      ent_approp_action eco_exit_date  exit_social  exit_knowledge  \
11                  3.0    2022-03-29          7.0             7.0
13                  6.0    2021-12-15          5.0             1.0
32                  2.0    2022-04-29          3.0             6.0
39                  7.0    2021-08-11          6.0             7.0
44                  6.0    2021-09-28          5.0             5.0
...                 ...           ...          ...             ...
8606                7.0    2022-04-05          7.0             7.0
8608                4.0    2021-06-09          3.0             1.0
8614                3.0    2021-08-04          6.0             4.0
8621                6.0    2022-02-10          7.0             7.0
8624                1.0    2021-05-12          3.0             3.0

      exit_approp_action  ... OC2 Data Check OC3 - a OC3 - b OC3 - c OC3 - d  \
11                   7.0  ...            1.0     NaN     NaN     NaN     1.0
13                   4.0  ...            1.0     NaN     1.0     NaN     NaN
32                   7.0  ...            1.0     NaN     NaN     NaN     1.0
39                   7.0  ...            1.0     NaN     NaN     NaN     NaN
44                   7.0  ...            1.0     NaN     NaN     NaN     NaN
...                  ...  ...            ...     ...     ...     ...     ...
8606                 7.0  ...            1.0     NaN     NaN     NaN     NaN
8608                 4.0  ...            1.0     NaN     1.0     NaN     NaN
8614                 5.0  ...            1.0     NaN     NaN     1.0     NaN
8621                 7.0  ...            1.0     NaN     NaN     NaN     NaN
8624                 1.0  ...            1.0     NaN     1.0     NaN     NaN

     OC3 - e OC3 Data Check  Days btw Initial and Exit  DBIexit  \
11       NaN            1.0                      836.0    834.0
13       NaN            1.0                      493.0    350.0
32       NaN            1.0                      356.0    343.0
39       1.0            1.0                      510.0    327.0
44       1.0            1.0                      501.0    340.0
...      ...            ...                        ...      ...
8606     1.0            1.0                      443.0    364.0
8608     NaN            1.0                      443.0    336.0
8614     NaN            1.0                      256.0    196.0
8621     1.0            1.0                      434.0    358.0
8624     NaN            1.0                      445.0    184.0

      Days btw I-IFSP to entry ECO
11                            23.0
13                            32.0
32                            20.0
39                             0.0
44                             0.0
...                            ...
8606                           0.0
8608                          14.0
8614                          13.0
8621                           0.0
8624                           0.0

[1243 rows x 60 columns]

In [ ]:
#eco_exit2

In [ ]:
eco_exit_2 = eco_exit[eco_exit['ent_social'] == 1.0]
eco_exit_2 = eco_exit[eco_exit['ent_knowledge'] == 1.0]
eco_exit_2 = eco_exit[eco_exit['ent_approp_action'] == 1.0]
eco_exit_2

In [ ]:
#SQL select count(ent_social), AVG (DBIexit)

In [ ]:
sql1 = 'SELECT count(ent_social), AVG(DBIexit) FROM eco_exit_1 WHERE ent_social = 3'
sqldf(sql1, globals())

In [ ]:
#python count

In [ ]:
eco_exit_count = eco_exit_1['ent_social'].value_counts
print(eco_exit_count)

In [ ]:
# SQL AVG improvemnt social

In [ ]:
sql2= 'SELECT AVG(exit_social - ent_social) as avg FROM eco_exit_2 WHERE ent_social = 3'
sqldf(sql2, globals())

In [ ]:
# python AVG imporovement

In [ ]:
social=(eco_exit_2['exit_social'].mean()- eco_exit_2['ent_social'])
social.mean()

In [ ]:
# SQL AVG improvement knowledge

In [ ]:
sql2= 'SELECT AVG(exit_knowledge - ent_knowledge) as knowledge_increase FROM eco_exit_2 WHERE ent_social = 3'
sqldf(sql2, globals())

In [ ]:
# python AVG improvement

In [ ]:
knowledge=(eco_exit_2['exit_knowledge'].mean()- eco_exit_2['ent_knowledge'])
knowledge.mean()

In [23]:
print(eco_exit_2['exit_social'].mean()/eco_exit_2['ent_social']*100)

0       112.045798
1        80.032713
3       280.114496
5       280.114496
6       140.057248
           ...
8624    186.742997
8626    560.228991
8627    560.228991
8628    140.057248
8630    140.057248
Name: ent_social, Length: 4629, dtype: float64

In [ ]:
#perent change

In [45]:
((eco_exit_2['ent_social'].mean()/eco_exit_2['exit_social'].mean()*100))

66.13581151428681

In [46]:
((eco_exit_2['ent_knowledge'].mean()/eco_exit_2['exit_knowledge'].mean()*100))

81.50946790806461

In [ ]:
((eco_exit_2['ent_knowledge'].mean()/eco_exit_2['exit_knowledge'].mean()*100))

In [47]:
print(eco_exit_2['ent_approp_action'].mean()/eco_exit_2['exit_approp_action']*100)

0       109.775329
1        62.728760
3        87.820264
5        62.728760
6        62.728760
           ...
8624    439.101318
8626     73.183553
8627     62.728760
8628     62.728760
8630     62.728760
Name: exit_approp_action, Length: 4629, dtype: float64