In [26]:
from pandasql import sqldf
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
project_data = pd.read_excel('../data/TEIS-NSS Project Data 10-2022.xlsx', 
                             sheet_name=['ECO with Exit21-22', 'Elig Timeline Rpt 2018-2022'])

eco_exit = project_data.get('ECO with Exit21-22')
elig_timeline = project_data.get('Elig Timeline Rpt 2018-2022')
print(eco_exit)
print(elig_timeline)

                                               DISTRICT  CHILD_ID  \
0                                                    ET  500335.0
1                                                    ET  479453.0
2                                                    ET  510663.0
3                                                    ET  452482.0
4                                                    ET  506507.0
...                                                 ...       ...
8631                                                 UC  514216.0
8632                                                NaN       NaN
8633                                                NaN       NaN
8634                                                NaN       NaN
8635  9/29/22 JM Corrected in TEIDS. Progress would ...       NaN

     ECO_Entry_DATE  Ent SOCIAL_SCALE  Ent KNOWLEDGE_SCALE  \
0        2021-04-23               5.0                  3.0
1        2020-03-23               7.0                  7.0
2               NaT               NaN                  NaN
3        2019-01-31               2.0                  3.0
4               NaT               NaN                  NaN
...             ...               ...                  ...
8631            NaT               NaN                  NaN
8632            NaT               NaN                  NaN
8633            NaT               NaN                  NaN
8634            NaT               NaN                  NaN
8635            NaT               NaN                  NaN

      Ent APPROPRIATE_ACTION_SCALE ECO_Exit_DATE  Exit SOCIAL_SCALE  \
0                              4.0    2021-10-23                6.0
1                              7.0    2021-08-19                7.0
2                              NaN           NaT                NaN
3                              3.0    2021-11-22                5.0
4                              NaN           NaT                NaN
...                            ...           ...                ...
8631                           NaN           NaT                NaN
8632                           NaN           NaT                NaN
8633                           NaN           NaT                NaN
8634                           NaN           NaT                NaN
8635                           NaN           NaT                NaN

      Exit KNOWLEDGE_SCALE  Exit APPROPRIATE_ACTION_SCALE  ... OC2 Data Check  \
0                      3.0                            4.0  ...            1.0
1                      7.0                            7.0  ...            1.0
2                      NaN                            NaN  ...            0.0
3                      3.0                            5.0  ...            1.0
4                      NaN                            NaN  ...            0.0
...                    ...                            ...  ...            ...
8631                   NaN                            NaN  ...            0.0
8632                   NaN                            NaN  ...            NaN
8633                   NaN                            NaN  ...            NaN
8634                   NaN                            NaN  ...            NaN
8635                   NaN                            NaN  ...            NaN

     OC3 - a OC3 - b OC3 - c OC3 - d OC3 - e OC3 Data Check  \
0        NaN     1.0     NaN     NaN     NaN            1.0
1        NaN     NaN     NaN     NaN     1.0            1.0
2        NaN     NaN     NaN     NaN     NaN            0.0
3        NaN     NaN     1.0     NaN     NaN            1.0
4        NaN     NaN     NaN     NaN     NaN            0.0
...      ...     ...     ...     ...     ...            ...
8631     NaN     NaN     NaN     NaN     NaN            0.0
8632     NaN     NaN     NaN     NaN     NaN            NaN
8633     NaN     NaN     NaN     NaN     NaN            NaN
8634     NaN     NaN     NaN     NaN     NaN            NaN
8635     NaN     NaN     NaN     NaN     NaN            NaN

      Days btw Initial and Exit  Days btw I-IFSP to Exit ECO  \
0                         206.0                        183.0
1                         704.0                        514.0
2                         115.0                     -44483.0
3                        1053.0                       1026.0
4                         159.0                     -44434.0
...                         ...                          ...
8631                       65.0                     -44537.0
8632                        NaN                          NaN
8633                        NaN                          NaN
8634                        NaN                          NaN
8635                        NaN                          NaN

      Days btw I-IFSP to entry ECO
0                              0.0
1                              0.0
2                         -44483.0
3                              0.0
4                         -44434.0
...                            ...
8631                      -44537.0
8632                           NaN
8633                           NaN
8634                           NaN
8635                           NaN

[8636 rows x 60 columns]
      District  Child ID Child Status  Child Phase Init. IFSP Due Date  \
0           ET    453926     Inactive         IFSP          2019-03-04
1           ET    431729     Inactive         IFSP          2018-10-26
2           ET    462474     Inactive         IFSP          2019-06-28
3           ET    446841     Inactive  Eligibility          2018-11-23
4           ET    459629     Inactive         IFSP          2019-05-16
...        ...       ...          ...          ...                 ...
67605       UC    509553     Inactive         IFSP          2021-10-03
67606       UC    509684     Inactive         IFSP          2021-10-07
67607       UC    526338     Inactive         IFSP          2022-05-22
67608       UC    511641     Inactive  Eligibility          2021-11-22
67609       UC    519977     Inactive         IFSP          2022-03-07

      IFSP Due Date IFSP Late Reason Active Ref. Date  \
0        2019-03-27           System       2019-01-18
1        2018-10-26              NaN       2018-09-11
2        2019-06-14              NaN       2019-05-14
3               NaT              NaN       2018-10-09
4        2019-04-24              NaN       2019-04-01
...             ...              ...              ...
67605    2021-10-22           System       2021-08-19
67606    2021-09-07              NaN       2021-08-23
67607    2022-05-05              NaN       2022-04-07
67608           NaT              NaN       2021-10-08
67609    2022-02-03              NaN       2022-01-21

      Parent Consent/Intake Date Date Dev. Evaluator Rec'd. Ref.  ...  \
0                     2019-02-04             2019-01-22 00:00:00  ...
1                     2018-09-25             2018-09-12 00:00:00  ...
2                     2019-05-30             2019-05-15 00:00:00  ...
3                     2018-10-25             2018-10-11 00:00:00  ...
4                     2019-04-10             2019-04-02 00:00:00  ...
...                          ...                             ...  ...
67605                 2021-08-26             2021-08-23 00:00:00  ...
67606                 2021-08-31             2021-08-24 00:00:00  ...
67607                 2022-04-10             2022-04-08 00:00:00  ...
67608                 2021-10-18             2021-10-11 00:00:00  ...
67609                 2022-01-26             2022-01-24 00:00:00  ...

      # Days Parent Consent to Dev. Eval.  \
0                                    17.0
1                                     0.0
2                                     0.0
3                                     0.0
4                                     0.0
...                                   ...
67605                                 0.0
67606                                 0.0
67607                                 1.0
67608                                 0.0
67609                                 0.0

      # Days Dev. Evaluator Assigned to Dev. Eval.  \
0                                             30.0
1                                             13.0
2                                             15.0
3                                             14.0
4                                              8.0
...                                            ...
67605                                          3.0
67606                                          7.0
67607                                          3.0
67608                                          7.0
67609                                          2.0

      1st Date Requested to Receipt of Med. Records  \
0                                               NaN
1                                               NaN
2                                               0.0
3                                               NaN
4                                               0.0
...                                             ...
67605                                          35.0
67606                                           0.0
67607                                           0.0
67608                                           NaN
67609                                           0.0

      # Days Dev. Eval. to Elig. Det. # Days Ref. to Elig. Det.  \
0                                 4.0                      38.0
1                                 6.0                      20.0
2                                 1.0                      17.0
3                                 1.0                      17.0
4                                 2.0                      11.0
...                               ...                       ...
67605                            47.0                      54.0
67606                             2.0                      10.0
67607                             2.0                       6.0
67608                            11.0                      21.0
67609                             5.0                      10.0

      Init. Elig. Decision                           Init. Elig. Category  \
0                 Eligible                       Developmental Evaluation
1                 Eligible  Diagnosed Condition, Developmental Evaluation
2                 Eligible                       Developmental Evaluation
3                 Eligible                            Diagnosed Condition
4                 Eligible                       Developmental Evaluation
...                    ...                                            ...
67605             Eligible  Diagnosed Condition, Developmental Evaluation
67606             Eligible                       Developmental Evaluation
67607             Eligible                       Developmental Evaluation
67608             Eligible                            Diagnosed Condition
67609             Eligible                       Developmental Evaluation

      Init. Elig. Det. Date  Exit Date  \
0                2019-02-25 2020-01-11
1                2018-10-01 2020-12-11
2                2019-05-31 2020-11-12
3                2018-10-26 2020-08-12
4                2019-04-12 2019-09-26
...                     ...        ...
67605            2021-10-12 2021-12-10
67606            2021-09-02 2022-03-07
67607            2022-04-13 2022-07-25
67608            2021-10-29 2022-06-22
67609            2022-01-31 2022-06-20

                                   Exit Reason
0                        618 - Part B eligible
1      618 - Part B eligibility not determined
2      618 - Part B eligibility not determined
3                               Parent decline
4                        618 - Parent withdraw
...                                        ...
67605                 618 - Moved out of state
67606                    618 - Parent withdraw
67607                    618 - Parent withdraw
67608                           Parent decline
67609                    618 - Part B eligible

[67610 rows x 38 columns]

In [35]:
eco_exit4= eco_exit.rename(columns={'Ent SOCIAL_SCALE' : 'Ent_Social_Scale', 'Exit SOCIAL_SCALE': 'Exit_Social_Scale'})

In [36]:
print(eco_exit4)

                                               DISTRICT  CHILD_ID  \
0                                                    ET  500335.0
1                                                    ET  479453.0
2                                                    ET  510663.0
3                                                    ET  452482.0
4                                                    ET  506507.0
...                                                 ...       ...
8631                                                 UC  514216.0
8632                                                NaN       NaN
8633                                                NaN       NaN
8634                                                NaN       NaN
8635  9/29/22 JM Corrected in TEIDS. Progress would ...       NaN

     ECO_Entry_DATE  Ent_Social_Scale  Ent KNOWLEDGE_SCALE  \
0        2021-04-23               5.0                  3.0
1        2020-03-23               7.0                  7.0
2               NaT               NaN                  NaN
3        2019-01-31               2.0                  3.0
4               NaT               NaN                  NaN
...             ...               ...                  ...
8631            NaT               NaN                  NaN
8632            NaT               NaN                  NaN
8633            NaT               NaN                  NaN
8634            NaT               NaN                  NaN
8635            NaT               NaN                  NaN

      Ent APPROPRIATE_ACTION_SCALE ECO_Exit_DATE  Exit_Social_Scale  \
0                              4.0    2021-10-23                6.0
1                              7.0    2021-08-19                7.0
2                              NaN           NaT                NaN
3                              3.0    2021-11-22                5.0
4                              NaN           NaT                NaN
...                            ...           ...                ...
8631                           NaN           NaT                NaN
8632                           NaN           NaT                NaN
8633                           NaN           NaT                NaN
8634                           NaN           NaT                NaN
8635                           NaN           NaT                NaN

      Exit KNOWLEDGE_SCALE  Exit APPROPRIATE_ACTION_SCALE  ... OC2 Data Check  \
0                      3.0                            4.0  ...            1.0
1                      7.0                            7.0  ...            1.0
2                      NaN                            NaN  ...            0.0
3                      3.0                            5.0  ...            1.0
4                      NaN                            NaN  ...            0.0
...                    ...                            ...  ...            ...
8631                   NaN                            NaN  ...            0.0
8632                   NaN                            NaN  ...            NaN
8633                   NaN                            NaN  ...            NaN
8634                   NaN                            NaN  ...            NaN
8635                   NaN                            NaN  ...            NaN

     OC3 - a OC3 - b OC3 - c OC3 - d OC3 - e OC3 Data Check  \
0        NaN     1.0     NaN     NaN     NaN            1.0
1        NaN     NaN     NaN     NaN     1.0            1.0
2        NaN     NaN     NaN     NaN     NaN            0.0
3        NaN     NaN     1.0     NaN     NaN            1.0
4        NaN     NaN     NaN     NaN     NaN            0.0
...      ...     ...     ...     ...     ...            ...
8631     NaN     NaN     NaN     NaN     NaN            0.0
8632     NaN     NaN     NaN     NaN     NaN            NaN
8633     NaN     NaN     NaN     NaN     NaN            NaN
8634     NaN     NaN     NaN     NaN     NaN            NaN
8635     NaN     NaN     NaN     NaN     NaN            NaN

      Days btw Initial and Exit  Days btw I-IFSP to Exit ECO  \
0                         206.0                        183.0
1                         704.0                        514.0
2                         115.0                     -44483.0
3                        1053.0                       1026.0
4                         159.0                     -44434.0
...                         ...                          ...
8631                       65.0                     -44537.0
8632                        NaN                          NaN
8633                        NaN                          NaN
8634                        NaN                          NaN
8635                        NaN                          NaN

      Days btw I-IFSP to entry ECO
0                              0.0
1                              0.0
2                         -44483.0
3                              0.0
4                         -44434.0
...                            ...
8631                      -44537.0
8632                           NaN
8633                           NaN
8634                           NaN
8635                           NaN

[8636 rows x 60 columns]

In [28]:
eco_exit2 = eco_exit.iloc[[3,4,5,7,8,9]]
print(eco_exit2)

  DISTRICT  CHILD_ID ECO_Entry_DATE  Ent SOCIAL_SCALE  Ent KNOWLEDGE_SCALE  \
3       ET  452482.0     2019-01-31               2.0                  3.0
4       ET  506507.0            NaT               NaN                  NaN
5       ET  494216.0     2021-01-06               2.0                  4.0
7       ET  494502.0     2021-03-01               6.0                  4.0
8       ET  488351.0     2020-09-15               5.0                  5.0
9       ET  489949.0     2020-10-20               2.0                  1.0

   Ent APPROPRIATE_ACTION_SCALE ECO_Exit_DATE  Exit SOCIAL_SCALE  \
3                           3.0    2021-11-22                5.0
4                           NaN           NaT                NaN
5                           6.0    2021-06-30                4.0
7                           5.0    2021-10-15                7.0
8                           7.0    2021-02-25                6.0
9                           2.0    2021-09-30                1.0

   Exit KNOWLEDGE_SCALE  Exit APPROPRIATE_ACTION_SCALE  ... OC2 Data Check  \
3                   3.0                            5.0  ...            1.0
4                   NaN                            NaN  ...            0.0
5                   5.0                            7.0  ...            1.0
7                   5.0                            6.0  ...            1.0
8                   5.0                            7.0  ...            1.0
9                   4.0                            5.0  ...            1.0

  OC3 - a OC3 - b OC3 - c OC3 - d OC3 - e OC3 Data Check  \
3     NaN     NaN     1.0     NaN     NaN            1.0
4     NaN     NaN     NaN     NaN     NaN            0.0
5     NaN     NaN     NaN     NaN     1.0            1.0
7     NaN     NaN     NaN     1.0     NaN            1.0
8     NaN     NaN     NaN     NaN     1.0            1.0
9     NaN     NaN     1.0     NaN     NaN            1.0

   Days btw Initial and Exit  Days btw I-IFSP to Exit ECO  \
3                     1053.0                       1026.0
4                      159.0                     -44434.0
5                      288.0                        175.0
7                      277.0                        228.0
8                      343.0                        163.0
9                      533.0                        345.0

   Days btw I-IFSP to entry ECO
3                           0.0
4                      -44434.0
5                           0.0
7                           0.0
8                           0.0
9                           0.0

[6 rows x 60 columns]

In [29]:
eco_exit3= eco_exit2.rename(columns={'Ent SOCIAL_SCALE' : 'Ent_Social_Scale', 'Exit SOCIAL_SCALE': 'Exit_Social_Scale'})

In [39]:
q = 'SELECT * FROM eco_exit3'
sqldf(q, globals())

,DISTRICT,CHILD_ID,ECO_Entry_DATE,Ent_Social_Scale,Ent KNOWLEDGE_SCALE,Ent APPROPRIATE_ACTION_SCALE,ECO_Exit_DATE,Exit_Social_Scale,Exit KNOWLEDGE_SCALE,Exit APPROPRIATE_ACTION_SCALE,...,OC2 Data Check,OC3 - a,OC3 - b,OC3 - c,OC3 - d,OC3 - e,OC3 Data Check,Days btw Initial and Exit,Days btw I-IFSP to Exit ECO,Days btw I-IFSP to entry ECO
0,ET,452482.0,2019-01-31 00:00:00.000000,2.0,3.0,3.0,2021-11-22 00:00:00.000000,5.0,3.0,5.0,...,1.0,None,None,1.0,NaN,NaN,1.0,1053.0,1026.0,0.0
1,ET,506507.0,None,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,None,None,NaN,NaN,NaN,0.0,159.0,-44434.0,-44434.0
2,ET,494216.0,2021-01-06 00:00:00.000000,2.0,4.0,6.0,2021-06-30 00:00:00.000000,4.0,5.0,7.0,...,1.0,None,None,NaN,NaN,1.0,1.0,288.0,175.0,0.0
3,ET,494502.0,2021-03-01 00:00:00.000000,6.0,4.0,5.0,2021-10-15 00:00:00.000000,7.0,5.0,6.0,...,1.0,None,None,NaN,1.0,NaN,1.0,277.0,228.0,0.0
4,ET,488351.0,2020-09-15 00:00:00.000000,5.0,5.0,7.0,2021-02-25 00:00:00.000000,6.0,5.0,7.0,...,1.0,None,None,NaN,NaN,1.0,1.0,343.0,163.0,0.0
5,ET,489949.0,2020-10-20 00:00:00.000000,2.0,1.0,2.0,2021-09-30 00:00:00.000000,1.0,4.0,5.0,...,1.0,None,None,1.0,NaN,NaN,1.0,533.0,345.0,0.0